### ISSUE TITLE
couldn't reproduce the results of CIFAR 10 dataset ?

### ISSUE THREAD

**Issue by bbdamodaran** [xingjunm/dimensionality-driven-learning#5]
Thanks for sharing the code. I couldn't reproduce the results for CIFAR 10 dataset.
I ran the train_models.py with following arguments:
    for dataset in ['cifar-10']:
        for noise_ratio in ['40']:#['0', '20', '40', '60']:
            args = parser.parse_args(['-d', dataset, '-m', 'd2l',
                               '-e', '120', '-b', '128',
                               '-r', noise_ratio])
    main(args)

I could get only 33% accuracy with 40% label noise. Please let me know the issues?

**Comment by xingjunm** [comment]
Hi Issues on CIFRA-10 has been fixed.
